#!/bin/sh
set -e
mkdir -p "../openbox_themes"
list_of_base_GTK_theme="$(cd baseGTK && ls)"
list_of_buttons="$(cd OBB && ls)"
current_path="$(cd .. && cd openbox_themes && pwd)"
cd .. && cd openbox_themes
for t in ${list_of_base_GTK_theme};do
    OBBname="${t#*_}"
    newthemename="${t%%_*}"
	mkdir -p "${newthemename}/openbox-3"
	cd "${newthemename}/openbox-3"
	ln -sf ../../../openbox_themes_creater/OBB/${OBBname}/* .
	cp -r ../../../openbox_themes_creater/baseGTK/${t} themerc
	cd "${current_path}"
done
