#!/bin/sh
list_of_base_GTK_theme="$(cd baseGTK && ls)"
list_of_buttons="$(cd OBB && ls)"
current_path="$(cd .. && cd themes && pwd)"
cd .. && cd themes
for t in ${list_of_base_GTK_theme};do
	for b in ${list_of_buttons};do
		newthemename="${t}${b}"
		mkdir -p "${newthemename}/openbox-3"
		cd "${newthemename}/openbox-3"
		ln -sf ../../../owl4ce/OBB/${b}/* .
		cp -r ../../../owl4ce/baseGTK/${t} themerc
		cd "${current_path}"
	done
done
